language: node_js
node_js:
- 6
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm run buildAvalon
script:
- npm run build

addons:
  code_climate:
    repo_token: cecb8ec105dc8e4b3f298312502f078a646f46ff
after_success:
- cat ./test/coverage/lcov.info | ./node_modules/.bin/coveralls