language: node_js
node_js:
- 8
branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm run lint
- karma start test/unit/karma.sauce.conf.js firefox && 
  karma start test/unit/karma.sauce.conf.js chrome && 
  karma start test/unit/karma.sauce.conf.js ie && 
  karma start test/unit/karma.sauce.conf.js safari && 
  karma start test/unit/karma.sauce.conf.js mobile
- npm run test:cov

after_success:
- cat ./test/coverage/lcov.info | ./node_modules/.bin/coveralls